/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author TIUNIDA 28
 */
public class Kelasku extends javax.swing.JFrame {

    /**
     * Creates new form Kelasku
     */
    public Kelasku() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        isiSetting.setEnabled(false);
        isiSetting.setVisible(false);
        setting1.setEnabled(false);
        setting1.setVisible(false);
        
        Power.setEnabled(false);
        Power.setVisible(false);
        Power1.setEnabled(false);
        Power1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BhsIndonesia = new javax.swing.JLabel();
        Kewarganegaraan = new javax.swing.JLabel();
        Alam = new javax.swing.JLabel();
        Agama = new javax.swing.JLabel();
        Matematika = new javax.swing.JLabel();
        Inggris = new javax.swing.JLabel();
        Shutdown = new javax.swing.JLabel();
        Dashboard = new javax.swing.JLabel();
        Peningkatan = new javax.swing.JLabel();
        News = new javax.swing.JLabel();
        Power = new javax.swing.JLabel();
        Power1 = new javax.swing.JLabel();
        Power2 = new javax.swing.JLabel();
        setting1 = new javax.swing.JLabel();
        setting2 = new javax.swing.JLabel();
        isiSetting = new javax.swing.JLabel();
        Games = new javax.swing.JLabel();
        Kelasku = new javax.swing.JLabel();
        Dashboard1 = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BhsIndonesia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BhsIndonesiaMouseClicked(evt);
            }
        });
        getContentPane().add(BhsIndonesia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 150, 110));

        Kewarganegaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KewarganegaraanMouseClicked(evt);
            }
        });
        getContentPane().add(Kewarganegaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 150, 110));

        Alam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlamMouseClicked(evt);
            }
        });
        getContentPane().add(Alam, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 150, 110));

        Agama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgamaMouseClicked(evt);
            }
        });
        getContentPane().add(Agama, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 150, 110));

        Matematika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatematikaMouseClicked(evt);
            }
        });
        getContentPane().add(Matematika, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, 110));

        Inggris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InggrisMouseClicked(evt);
            }
        });
        getContentPane().add(Inggris, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 150, 110));

        Shutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShutdownMouseClicked(evt);
            }
        });
        getContentPane().add(Shutdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 100, 20));

        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });
        getContentPane().add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 30));

        Peningkatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeningkatanMouseClicked(evt);
            }
        });
        getContentPane().add(Peningkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 30));

        News.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewsMouseClicked(evt);
            }
        });
        getContentPane().add(News, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 130, 30));

        Power.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi/img/Power.png"))); // NOI18N
        Power.setText("jLabel1");
        getContentPane().add(Power, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 130, 110));

        Power1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Power1MouseClicked(evt);
            }
        });
        getContentPane().add(Power1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 40, 40));

        Power2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Power2MouseClicked(evt);
            }
        });
        getContentPane().add(Power2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 40, 40));

        setting1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setting1MouseClicked(evt);
            }
        });
        getContentPane().add(setting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 40, 40));

        setting2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setting2MouseClicked(evt);
            }
        });
        getContentPane().add(setting2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 40, 40));

        isiSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi/img/Setting.png"))); // NOI18N
        getContentPane().add(isiSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 130, 110));

        Games.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GamesMouseClicked(evt);
            }
        });
        getContentPane().add(Games, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        Kelasku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KelaskuMouseClicked(evt);
            }
        });
        getContentPane().add(Kelasku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 130, 30));
        getContentPane().add(Dashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 30));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi/img/Kelasku.png"))); // NOI18N
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setting1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setting1MouseClicked
        isiSetting.setEnabled(false);
        isiSetting.setVisible(false);
        setting1.setEnabled(false);
        setting1.setVisible(false);
        setting2.setEnabled(true);
        setting2.setVisible(true);
    }//GEN-LAST:event_setting1MouseClicked

    private void setting2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setting2MouseClicked
        isiSetting.setEnabled(true);
        isiSetting.setVisible(true);
        setting1.setEnabled(true);
        setting1.setVisible(true);
        setting2.setEnabled(false);
        setting2.setVisible(false);
    }//GEN-LAST:event_setting2MouseClicked

    private void Power1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Power1MouseClicked
        Power.setEnabled(false);
        Power.setVisible(false);
        Power1.setEnabled(false);
        Power1.setVisible(false);
        Power2.setEnabled(true);
        Power2.setVisible(true);
    }//GEN-LAST:event_Power1MouseClicked

    private void Power2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Power2MouseClicked
        Power.setEnabled(true);
        Power.setVisible(true);
        Power1.setEnabled(true);
        Power1.setVisible(true);
        Power2.setEnabled(false);
        Power2.setVisible(false);
    }//GEN-LAST:event_Power2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        for (double i = 0.0; i <=1.0;i = i+ 0.1)
//        {
//            String val = i+ "";
//            float f = Float.valueOf(val);
//            this.setOpacity(f);
//            try{
//                Thread.sleep(50);
//            }
//            catch(Exception e)
//            {
//                
//            }
//        }
    }//GEN-LAST:event_formWindowOpened

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DashboardMouseClicked

    private void GamesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GamesMouseClicked
        Games game = new Games();
        game.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GamesMouseClicked

    private void KelaskuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KelaskuMouseClicked
        Kelasku kelas = new Kelasku();
        kelas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_KelaskuMouseClicked

    private void ShutdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShutdownMouseClicked
        int selectedOption = JOptionPane.showConfirmDialog(null,
            "Apakah anda ingin menutup Intuisi Kita?", "Exit Intuisi Kita", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ShutdownMouseClicked

    private void NewsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewsMouseClicked
        News news = new News();
        news.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NewsMouseClicked

    private void PeningkatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeningkatanMouseClicked
        Peningkatan peningkatan = new Peningkatan();
        peningkatan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PeningkatanMouseClicked

    private void MatematikaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatematikaMouseClicked
        Matematika mtk = new Matematika();
        mtk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MatematikaMouseClicked

    private void BhsIndonesiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BhsIndonesiaMouseClicked
        BhsIndonesia ind = new BhsIndonesia();
        ind.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BhsIndonesiaMouseClicked

    private void KewarganegaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KewarganegaraanMouseClicked
        Kewarganegaraan pkn = new Kewarganegaraan();
        pkn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_KewarganegaraanMouseClicked

    private void AlamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlamMouseClicked
        Alam alam = new Alam();
        alam.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AlamMouseClicked

    private void AgamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgamaMouseClicked
        Agama agama = new Agama();
        agama.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AgamaMouseClicked

    private void InggrisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InggrisMouseClicked
        Inggris ing = new Inggris();
        ing.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InggrisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kelasku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kelasku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kelasku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kelasku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kelasku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agama;
    private javax.swing.JLabel Alam;
    private javax.swing.JLabel BhsIndonesia;
    private javax.swing.JLabel Dashboard;
    private javax.swing.JLabel Dashboard1;
    private javax.swing.JLabel Games;
    private javax.swing.JLabel Inggris;
    private javax.swing.JLabel Kelasku;
    private javax.swing.JLabel Kewarganegaraan;
    private javax.swing.JLabel Matematika;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel News;
    private javax.swing.JLabel Peningkatan;
    private javax.swing.JLabel Power;
    private javax.swing.JLabel Power1;
    private javax.swing.JLabel Power2;
    private javax.swing.JLabel Shutdown;
    private javax.swing.JLabel isiSetting;
    private javax.swing.JLabel setting1;
    private javax.swing.JLabel setting2;
    // End of variables declaration//GEN-END:variables
}
